import time
import random
from db_connect import get_conn

conn = get_conn().raw_connection()
cursor = conn.cursor()

cursor.execute("DROP TABLE IF EXISTS account")
cursor.execute("""
CREATE TABLE account(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch INT NOT NULL,
    balance FLOAT NOT NULL)
""")

for i in xrange(0, 100000):
    account = random.randint(1, 20)
    balance = round(random.uniform(0, 100000), 2)
    cursor.execute("""INSERT INTO account VALUES (DEFAULT, %d,%f)""" % (account, balance))

conn.commit()

