SELECT LINEITEM.L_ORDERKEY, PART.P_NAME, SUPPLIER.S_NAME, ORDERS.O_ORDERDATE, LINEITEM.L_EXTENDEDPRICE
FROM LINEITEM, ORDERS, CUSTOMER, SUPPLIER, PART
WHERE CUSTOMER.C_NAME = 'Customer#000000001'
AND CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
AND ORDERS.O_ORDERKEY = LINEITEM.L_ORDERKEY
AND LINEITEM.L_SUPPKEY = SUPPLIER.S_SUPPKEY
AND LINEITEM.L_PARTKEY = PART.P_PARTKEY